### ISSUE TITLE
Missing indexes for Prisma schema

### ISSUE THREAD

**Issue by pstachula-dev** [drizzle-team/drizzle-benchmarks#6]
This comparison is unfair because Drizzle has applied index optimizations that Schema Prisma lacks.

https://www.prisma.io/docs/orm/reference/prisma-schema-reference#index

**Comment by AndriiSherman** [comment]
Which index exactly?

**Comment by AndriiSherman** [comment]
It's fair because we are seeding both databases with Drizzle migration scripts, and the Prisma schema simply represents models for us to query.

As you can see from the README, you should use the [pnpm seed:start](https://github.com/drizzle-team/drizzle-benchmarks/blob/main/package.json#L8) script, which executes the migrate from the drizzle folder (refer to the [source code](https://github.com/drizzle-team/drizzle-benchmarks/blob/main/src/seed.ts#L118)).

This script utilizes two migration files:

- https://github.com/drizzle-team/drizzle-benchmarks/blob/main/drizzle/0000_flat_master_mold.sql
- https://github.com/drizzle-team/drizzle-benchmarks/blob/main/drizzle/0001_concerned_mother_askani.sql

These files include indexes for both Drizzle and Prisma, ensuring fair tests. You can run them yourself to confirm that they operate against indexed databases for both libraries.
